// Code generated by "stringer -type Kind kind.go"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SQLKeyword-0]
	_ = x[Number-1]
	_ = x[Char-2]
	_ = x[SingleQuotedString-3]
	_ = x[NationalStringLiteral-4]
	_ = x[Comma-5]
	_ = x[Whitespace-6]
	_ = x[Comment-7]
	_ = x[MultilineComment-8]
	_ = x[Eq-9]
	_ = x[Neq-10]
	_ = x[Lt-11]
	_ = x[Gt-12]
	_ = x[LtEq-13]
	_ = x[GtEq-14]
	_ = x[Plus-15]
	_ = x[Minus-16]
	_ = x[Mult-17]
	_ = x[Div-18]
	_ = x[Caret-19]
	_ = x[Mod-20]
	_ = x[LParen-21]
	_ = x[RParen-22]
	_ = x[Period-23]
	_ = x[Colon-24]
	_ = x[DoubleColon-25]
	_ = x[Semicolon-26]
	_ = x[Backslash-27]
	_ = x[LBracket-28]
	_ = x[RBracket-29]
	_ = x[Ampersand-30]
	_ = x[LBrace-31]
	_ = x[RBrace-32]
	_ = x[ILLEGAL-33]
}

const _Kind_name = "SQLKeywordNumberCharSingleQuotedStringNationalStringLiteralCommaWhitespaceCommentMultilineCommentEqNeqLtGtLtEqGtEqPlusMinusMultDivCaretModLParenRParenPeriodColonDoubleColonSemicolonBackslashLBracketRBracketAmpersandLBraceRBraceILLEGAL"

var _Kind_index = [...]uint8{0, 10, 16, 20, 38, 59, 64, 74, 81, 97, 99, 102, 104, 106, 110, 114, 118, 123, 127, 130, 135, 138, 144, 150, 156, 161, 172, 181, 190, 198, 206, 215, 221, 227, 234}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
